### ISSUE TITLE
Function for plots should be fine

### ISSUE THREAD

**Issue by timothy1191xa** [berkeley-stat159/project-epsilon#238]
Hello @soazig @mingujo @lizhua @ye-zhi 

Matthew replied - 

Don't worry too much about the absolute value for the coverage. It's hard to do tests for the plots. We'll look at what code you haven't covered, and take into account if it was hard to cover.

So can I just merge it if the friggin Travis only shows that I would lower the coverage but no error?

**Comment by soazig** [comment]
I would turn it into a script and put it in utils/script and not utils/functions.
Because it will be hard to control the remaining functions and tests we want to add if the coverage goes lower than 100%.
At the end, I also would like to add the scripts in the coverage but we will be able to select which script to cover at that point.
